# Generated by Django 3.1.4 on 2020-12-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('zone', models.CharField(max_length=200)),
                ('time', models.TimeField(auto_now_add=True)),
                ('people_frequency', models.IntegerField(default=0)),
                ('police_station', models.BooleanField(default=True)),
                ('bar', models.BooleanField(default=False)),
            ],
        ),
    ]
